### ISSUE TITLE
Null coalescing operator within template string literal breaks syntax highlighting

### ISSUE THREAD

**Issue by bsmith-cycorp** [michaelgmcd/vscode-language-babel#42] opened 2019-02-20 21:41 UTC
<img width="347" alt="untitled-3_ _cyc-ui" src="https://user-images.githubusercontent.com/25161635/53126420-b21fc780-3525-11e9-811e-d65bfbfa7fbc.png">

This seems to be new as-of VSCode 1.31; we've had cases like this in our code for months and I only noticed the problem today. The problem doesn't happen after removing the `??` (and the following value).

**Comment by pizza-r0b** [comment] 2019-02-20 23:18
Ran into this as well.

**Comment by bsmith-cycorp** [comment] 2019-02-21 19:55
Update: reverting to VSCode v1.30 did not fix this, but reverting this extension to v0.0.21 did.

**Comment by michaelgmcd** [comment] 2019-02-22 16:38
Yep, it looks like this was a regression in 0.0.22. I'll look into this when I can. Some of the work in 0.0.22 is required for #33.

**Comment by bsmith-cycorp** [comment] 2019-02-22 17:08
Fortunately VSCode now has a very easy way to revert an extension: find the extension in the extensions view, right-click it, and click "Install Another Version..."

**Comment by michaelgmcd** [comment] 2019-07-31 03:38
Was this fixed in the latest release?

**Comment by michaelgmcd** [comment] 2019-07-31 23:54
This issue is fixed in the latest release.

**Closed** 2019-07-31 23:54 UTC
