### ISSUE TITLE
Syntax highlighter confused by generic arguments in function calls

### ISSUE THREAD

**Issue by kevinbarabash** [michaelgmcd/vscode-language-babel#57] opened 2019-09-01 22:54 UTC
The syntax highlighter gets confused when it runs into a type parameter in a generic function call.

<img width="381" alt="Screen Shot 2019-09-01 at 6 51 58 PM" src="https://user-images.githubusercontent.com/1044413/64083208-b7867780-cce9-11e9-8c54-61e9b7eff7f5.png">

```js
type D = () => mixed;

const Foo = () => {
  const dispatch = useDispatch();

  return (
    <div>Hello, world!</div>
  )
};

const Bar = () => {
  const dispatch = useDispatch<D>();

  return (
    <div>Hello, world!</div>
  )
};
```

**Comment by mgtitimoli** [comment] 2019-09-10 21:53
Duplicate of #43

**Closed** 2019-09-10 22:55 UTC

**Comment by kevinbarabash** [comment] 2019-09-10 22:57
That issue was closed by a PR.  Does there need to be a publish before that update will appear in the plugin in VSCode?

**Comment by michaelgmcd** [comment] 2019-09-11 15:30
Please check that this was fixed in v0.0.24

**Comment by kevinbarabash** [comment] 2019-09-11 22:23
@michaelgmcd it's fixed.  Thanks for publishing and thanks for writing this plugin.
