### ISSUE TITLE
loses auto-indent

### ISSUE THREAD

**Issue by rjohnep** [michaelgmcd/vscode-language-babel#21] opened 2018-03-21 13:55 UTC
VSCode Version: 1.21.1
Mac OS High Sierra 10.13.3

Open a JavaScript file
Type <div>

auto-indent is lost

![26846989-52303ff0-4ab0-11e7-85fa-07af171051c1](https://user-images.githubusercontent.com/17835803/37713689-bb3d2534-2d28-11e8-84b9-a167826db83b.png)

**Comment by swashata** [comment] 2018-03-26 15:00
I can also confirm this. I was trying on JSX files. I couldn't auto indent any components

```jsx
<View>
|</View>
```

But without this extension

```jsx
<View>
    |
</View>
```

**Comment by michaelgmcd** [comment] 2018-03-26 19:32
This extension does not provide auto-closing behavior so I'm guessing it's a problem with the integration with this extension and whatever library you're both using. I'm assuming it's https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag

**Comment by michaelgmcd** [comment] 2018-03-26 19:51
VSCode supported this in https://github.com/Microsoft/vscode/commit/d12f86565089522a0bc65633d443c7fd3a04026d. It requires me to change the name of the syntax languages to be the same as theres. 'll push out a fix for this today.

**Comment by swashata** [comment] 2018-03-27 04:24
Hello,

Has this been resolved? I see the commit got reverted...

**Comment by michaelgmcd** [comment] 2018-03-27 17:53
Yes, I thought I had a fix, but turned out to cause some regressions. This is difficult because VSCode's support for this is tightly coupled to their own javascript syntax highlighting. I'm hoping to be able to support this sometime this week or weekend.

**Comment by jaybyrrd** [comment] 2018-07-07 20:37
Hey, I just wanted to let you know this is driving me a bit crazy and I would appreciate a fix greatly. <3

**Comment by kykungz** [comment] 2018-07-14 14:29
I'm moving from Atom and having this problem too. Does anyone have a workaround yet? or every vscode users are fine with this.

**Comment by swashata** [comment] 2018-07-14 14:39
For now, I am just using the default vscode javascript (and javascript react) syntax. It works pretty good.

**Comment by michaelgmcd** [comment] 2018-07-14 17:18
I'm still looking into solutions for this. Would love a PR!

**Comment by michaelgmcd** [comment] 2018-07-15 20:57
This should be fixed in the latest release.

**Closed by michaelgmcd** 2018-07-15 20:57 UTC
